#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --distribution bullseye \
    --architectures amd64 \
    --debian-installer live \
    --archive-areas "main contrib non-free" \
    --backports true \
    --mirror-bootstrap http://deb.debian.org/debian/ \
    --mirror-binary http://deb.debian.org/debian/ \
	"${@}"
